kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.externalServiceName }}
  namespace: {{ .Release.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.server.protocol }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingressVirtualHost }}
    secretName: {{ .Values.externalServiceName }}-tls-secret
  rules:
  - host: {{ .Values.ingressVirtualHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.externalServiceName }}
            port:
              number: {{ .Values.server.port }}
