apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.externalServiceName }}
  namespace: {{ .Release.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.server.address }}
  ports:
  - port: {{ .Values.server.port }}
