defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: false
    configReloaders: true
    general: false
    k8s: false
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubeControllerManager: false
    kubelet: false
    kubeProxy: false
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeStateMetrics: false
    network: false
    node: false
    nodeExporterAlerting: false
    nodeExporterRecording: false
    prometheus: true
    prometheusOperator: true

grafana:
  enabled: true
  adminPassword: "${grafana_admin_password}"
  defaultDashboardsTimezone: US/Eastern
  ingress:
    enabled: true
    annotations:
      "kubernetes.io/ingress.class": "nginx"
      "cert-manager.io/cluster-issuer": "lets-encrypt"
    hosts:
      - "grafana.${external_domain_name}"
    path: "/"
    tls:
      - secretName: grafana-tls-secret
        hosts:
          - "grafana.${external_domain_name}"

alertmanager:
  enabled: true
  # blank out of the default AlertManager configuration
  config:

  config:
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname','cluster','namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "${alert_receiver_name}"
      routes:
        - receiver: "${alert_receiver_name}"

    receivers:
      - name: "${alert_receiver_name}"
        webhook_configs:
          - url: "${alert_receiver_url}"
            send_resolved: true
            http_config:
              basic_auth:
                username: ${alert_receiver_username}
                password: ${alert_receiver_password}

    templates:
      - '/etc/alertmanager/config/*.tmpl'

kubelet:
  enabled: true

kubeControllerManager:
  enabled: true

coreDns:
  enabled: true

kubeEtcd:
  enabled: true

kubeScheduler:
  enabled: true

kubeProxy:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false
