---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: default
  namespace: "${namespace}"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      dns01:
        cloudflare:
          email: "${certificate_mail}"
          apiTokenSecretRef:
            name: cloudflare-api-secret
            key: token
...
