postgresql:
  enabled: false

artifactory:
  postgresql:
    enabled: false

  ingress:
    enabled: true
    hosts:
      - "repo.${external_domain_name}"
    annotations:
      cert-manager.io/cluster-issuer: lets-encrypt
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    tls:
      - secretName: artifactory-tls-secret
        hosts:
          - "repo.${external_domain_name}"

  nginx:
    enabled: false
