grafana:
  enabled: true
  adminPassword: "${grafana_admin_password}"
  defaultDashboardsTimezone: US/Eastern
  ingress:
    enabled: true
    annotations:
      "kubernetes.io/ingress.class": "nginx"
      "cert-manager.io/cluster-issuer": "lets-encrypt"
    hosts:
      - "grafana.${domain_name}"
    path: "/"
    tls:
      - secretName: grafana-tls-secret
        hosts:
          - "grafana.${domain_name}"

alertmanager:
  enabled: false

kubelet:
  enabled: true

kubeControllerManager:
  enabled: false

coreDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false
